"""add_max_answer_length_to_test_cases

Revision ID: cfb50dd8225a
Revises: 025
Create Date: 2026-03-19 20:15:26.396685
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cfb50dd8225a'
down_revision: Union[str, None] = '025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('max_answer_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'max_answer_length')
    # ### end Alembic commands ###
