/**
 * API client for LoopLM backend.
 * Re-exports all types and functions so existing imports continue working.
 */

// Re-export all types
export type {
  TestDatasetItem,
  TestDatasetListResponse,
  TestCaseItem,
  TestDatasetDetail,
  TestCaseSuggestion,
  TestCaseCreateBody,
  TestDatasetExport,
  EvaluatorItem,
  EvaluatorListResponse,
  EvaluatorCreateBody,
  EvaluatorUpdateBody,
  Project,
  DashboardStats,
  Integration,
  CreateIntegrationBody,
  UpdateIntegrationBody,
  IngestKey,
  IngestKeyCreated,
  TraceListResponse,
  TraceListItem,
  ThreadSummary,
  ThreadListResponse,
  SpanNode,
  TraceDetail,
  TraceTreeNode,
  TraceChildrenResponse,
  TraceAnalysis,
  TraceFeedbackScore,
  AggregateGraphNode,
  AggregateGraphEdge,
  AggregateGraphResponse,
  RouteNode,
  RouteEdge,
  RouteAnalysisResponse,
  BottleneckNode,
  BottleneckResponse,
  Suggestion,
  AdvisorResponse,
  AdvisorRunResponse,
  AdvisorRunTrigger,
  AdvisorProgressLogEntry,
  PromptItem,
  PromptListResponse,
  AntiPattern,
  PromptReviewResult,
  PromptReviewListResponse,
  FeedbackScoreItem,
  FeedbackListResponse,
  FeedbackTrend,
  GraderStats,
  FeedbackStatsResponse,
  FeedbackScoreDetail,
  FeedbackEvalItem,
  FeedbackEvalSummary,
  FeedbackEvaluateResponse,
  FeedbackEvaluatorConfig,
  TopQuestionTheme,
  TopQuestionsResponse,
  SuggestionRunResponse,
  GraderSummaryItem,
  ScoreSummaryItem,
  EvalRunListItem,
  EvalRunListResponse,
  EvalGraderResult,
  ConversationTurn,
  EvalResultItem,
  EvalResultSummary,
  RootCauseDetail,
  GraderResultSummary,
  EvalRunDetail,
  EvalRunStats,
  DatasetPickerItem,
  DatasetPickerResponse,
  EvalJob,
  EvalJobListResponse,
  EvalJobLogsResponse,
  TriggerEvalResponse,
  JsonImportItem,
  JsonImportListResponse,
  EvalReportResponse,
  CodeSuggestionItem,
  OpenCodeAnalysisResponse,
  Experiment,
  ExperimentListResponse,
  ExperimentCreateBody,
  ExperimentUpdateBody,
  EvalSession,
  EvalSessionListResponse,
  TriggerSessionResponse,
  CostSummaryResponse,
  CostTrendResponse,
  CostDetailsResponse,
  CostDetailItem,
  ServiceCostBreakdown,
  ModelCostBreakdown,
  CostTrendPoint,
  CostsOverviewResponse,
  CostOverviewTrendPoint,
  ModelCostItem,
  ServiceCostItem,
  RequestOutcome,
  RequestClusterTheme,
  RequestClustersResponse,
  RetrievalSource,
  RetrievalActivityPoint,
} from "./api-types";

// Re-export all functions from domain modules
export * from "./api/client";
export * from "./api/traces-api";
export * from "./api/prompts-api";
export * from "./api/feedback-api";
export * from "./api/evals-api";
export * from "./api/experiments-api";
export * from "./api/evaluators-api";
export * from "./api/datasets-api";
export * from "./api/code-agent-api";
export * from "./api/github-api";
export * from "./api/costs-api";
export * from "./api/analytics-api";
export * from "./api/version";
export * from "./api/admin";
